const Projects = [
  {
    Id: "1",
    pTitle: "Architecture",
    slug: "Architecture",
    pImg: "/images/project/4.jpg",
    pSImg: "/images/project-single/img-1.jpg",
    ssImg1: "/images/project-single/2.jpg",
    ssImg2: "/images/project-single/3.jpg",
  },
  {
    Id: "2",
    pTitle: "Exterior Design",
    slug: "Exterior-Design",
    pImg: "/images/project/5.jpg",
    pSImg: "/images/project-single/img-2.jpg",
    ssImg1: "/images/project-single/2.jpg",
    ssImg2: "/images/project-single/3.jpg",
  },
  {
    Id: "3",
    pTitle: "Interior",
    slug: "Interior",
    pImg: "/images/project/6.jpg",
    pSImg: "/images/project-single/img-3.jpg",
    ssImg1: "/images/project-single/2.jpg",
    ssImg2: "/images/project-single/3.jpg",
  },
  {
    Id: "4",
    pTitle: "Furniture & Decor",
    slug: "Furniture-&-Decor",
    pImg: "/images/project/7.jpg",
    pSImg: "/images/project-single/img-4.jpg",
    ssImg1: "/images/project-single/2.jpg",
    ssImg2: "/images/project-single/3.jpg",
  },
  {
    Id: "5",
    pTitle: "Modern Architecture in London",
    slug: "Modern-Architecture-in-London",
    pImg: "/images/project/1.jpg",
    pSImg: "/images/project-single/img-5.jpg",
    ssImg1: "/images/project-single/2.jpg",
    ssImg2: "/images/project-single/3.jpg",
  },
  {
    Id: "6",
    pTitle: "Interior Design in San Francisco",
    slug: "Interior-Design-in-San-Francisco",
    pImg: "/images/project/2.jpg",
    pSImg: "/images/project-single/img-6.jpg",
    ssImg1: "/images/project-single/2.jpg",
    ssImg2: "/images/project-single/3.jpg",
  },
  {
    Id: "7",
    pTitle: "Exclusive Home Decor in California",
    slug: "Exclusive-Home-Decor-in-California",
    pImg: "/images/project/3.jpg",
    pSImg: "/images/project-single/img-7.jpg",
    ssImg1: "/images/project-single/2.jpg",
    ssImg2: "/images/project-single/3.jpg",
  },
  {
    Id: "8",
    pTitle: "Interior Design in San Francisco",
    slug: "Interior-Design-in-San-Francisco",
    pImg: "/images/project/2.jpg",
    pSImg: "/images/project-single/img-6.jpg",
    ssImg1: "/images/project-single/2.jpg",
    ssImg2: "/images/project-single/3.jpg",
  },
];

export default Projects;
