const Services = [
  {
    Id: "1",
    sImg: "/images/service/icon-1.svg",
    scImg: "/images/service/1.svg",
    sSimg: "/images/service-single/img-1.jpg",
    sTitle: "Design & Planning",
    slug: "Design-&-Planning",
    description:
      "Noimy donecing and vivamus vitae commodo. Ut purus ornare laoreet ultrices are sitac",
    des2: "Elementum aliquam byuerirra sagittis duis non quis.",
    des3: "One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities",
    ssImg1: "/images/service-single/2.jpg",
    ssImg2: "/images/service-single/3.jpg",
  },
  {
    Id: "2",
    sImg: "/images/service/icon-2.svg",
    scImg: "/images/service/2.svg",
    sSimg: "/images/service-single/img-2.jpg",
    sTitle: "Custom Solutions",
    slug: "Custom-Solutions",
    description:
      "Noimy donecing and vivamus vitae commodo. Ut purus ornare laoreet ultrices are sitac",
    des2: "Elementum aliquam byuerirra sagittis duis non quis.",
    des3: "One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities",
    ssImg1: "/images/service-single/2.jpg",
    ssImg2: "/images/service-single/3.jpg",
  },
  {
    Id: "3",
    sImg: "/images/service/icon-3.svg",
    scImg: "/images/service/3.svg",
    sSimg: "/images/service-single/img-3.jpg",
    sTitle: "Furniture & Decor",
    slug: "Furniture-&-Decor",
    description:
      "Noimy donecing and vivamus vitae commodo. Ut purus ornare laoreet ultrices are sitac",
    des2: "Elementum aliquam byuerirra sagittis duis non quis.",
    des3: "One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities",
    ssImg1: "/images/service-single/2.jpg",
    ssImg2: "/images/service-single/3.jpg",
  },
  {
    Id: "4",
    sImg: "/images/service/icon-4.svg",
    scImg: "/images/service/4.svg",
    sSimg: "/images/service-single/img-4.jpg",
    sTitle: "Exterior Design",
    slug: "Exterior-Design",
    description:
      "Noimy donecing and vivamus vitae commodo. Ut purus ornare laoreet ultrices are sitac",
    des2: "Elementum aliquam byuerirra sagittis duis non quis.",
    des3: "One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities",
    ssImg1: "/images/service-single/2.jpg",
    ssImg2: "/images/service-single/3.jpg",
  },
  {
    Id: "5",
    sImg: "/images/service/icon-5.svg",
    scImg: "/images/service/5.svg",
    sSimg: "/images/service-single/img-5.jpg",
    sTitle: "Interior Design",
    slug: "Interior-Design",
    description:
      "Noimy donecing and vivamus vitae commodo. Ut purus ornare laoreet ultrices are sitac",
    des2: "Elementum aliquam byuerirra sagittis duis non quis.",
    des3: "One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities",
    ssImg1: "/images/service-single/2.jpg",
    ssImg2: "/images/service-single/3.jpg",
  },
  {
    Id: "6",
    sImg: "/images/service/icon-6.svg",
    scImg: "/images/service/6.svg",
    sSimg: "/images/service-single/img-6.jpg",
    sTitle: "Concept Planning",
    slug: "Concept-Planning",
    description:
      "Noimy donecing and vivamus vitae commodo. Ut purus ornare laoreet ultrices are sitac",
    des2: "Elementum aliquam byuerirra sagittis duis non quis.",
    des3: "One way to categorize the activities is in terms of the professional’s area of expertise such as competitive analysis, corporate strategy the activities",
    ssImg1: "/images/service-single/2.jpg",
    ssImg2: "/images/service-single/3.jpg",
  },
];
export default Services;
